// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuawXwApiCdSEvFJmCc5d2oUNf69nBnLU',
    appId: '1:380051548248:web:a5f7bc7bb2b9f8c071c22d',
    messagingSenderId: '380051548248',
    projectId: 'lenteracafee-e3be8',
    authDomain: 'lenteracafee-e3be8.firebaseapp.com',
    storageBucket: 'lenteracafee-e3be8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBynob_Cb3Uhn7Y7PM1pngJY14jiGKi21A',
    appId: '1:380051548248:android:2327794dfd13e44471c22d',
    messagingSenderId: '380051548248',
    projectId: 'lenteracafee-e3be8',
    storageBucket: 'lenteracafee-e3be8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpAuxq6XgmzWfkYJRrKmP4n9BhkdzZn_I',
    appId: '1:380051548248:ios:d1d47a2860a70e1471c22d',
    messagingSenderId: '380051548248',
    projectId: 'lenteracafee-e3be8',
    storageBucket: 'lenteracafee-e3be8.firebasestorage.app',
    iosBundleId: 'com.example.lenteracafe',
  );
}
